//// Generated by spider on 2020-05-08 16:49:04.368811

import 'dart:io';

import 'package:covid19/res/asset_images.dart';
import 'package:test/test.dart';

void main() {
  test('asset_images assets test', () {
    expect(true, File(AssetImages.noInternet).existsSync());
    expect(true, File(AssetImages.fact).existsSync());
    expect(true, File(AssetImages.genericError).existsSync());
    expect(true, File(AssetImages.myth).existsSync());
  });
}
