//// Generated by spider on 2020-04-24 13:24:13.974848

import 'dart:io';

import 'package:covid19/res/asset_images.dart';
import 'package:test/test.dart';

void main() {
  test('asset_images assets test', () {
    expect(true, File(AssetImages.runnyNose).existsSync());
    expect(true, File(AssetImages.fever).existsSync());
    expect(true, File(AssetImages.noInternet).existsSync());
    expect(true, File(AssetImages.fact).existsSync());
    expect(true, File(AssetImages.home).existsSync());
    expect(true, File(AssetImages.mythBusters).existsSync());
    expect(true, File(AssetImages.covid19AGlobalHealthCrisis).existsSync());
    expect(true, File(AssetImages.virus).existsSync());
    expect(true, File(AssetImages.tierdness).existsSync());
    expect(true, File(AssetImages.prevention).existsSync());
    expect(true, File(AssetImages.splash).existsSync());
    expect(true, File(AssetImages.statistics).existsSync());
    expect(true, File(AssetImages.nasalCongestion).existsSync());
    expect(true, File(AssetImages.covid19PreventionDosAndDonts).existsSync());
    expect(true, File(AssetImages.genericError).existsSync());
    expect(true, File(AssetImages.soreThroat).existsSync());
    expect(true, File(AssetImages.cough).existsSync());
    expect(true, File(AssetImages.faq).existsSync());
    expect(true, File(AssetImages.difficultyBreathing).existsSync());
    expect(true, File(AssetImages.myth).existsSync());
    expect(true, File(AssetImages.fatigue).existsSync());
    expect(true, File(AssetImages.headache).existsSync());
    expect(true, File(AssetImages.symptoms).existsSync());
  });
}
