//// Generated by spider on 2020-04-26 22:41:30.720606

class AssetImages {
  static const String runnyNose = 'assets/images/runny-nose.png';
  static const String fever = 'assets/images/fever.png';
  static const String noInternet = 'assets/images/no-internet.png';
  static const String fact = 'assets/images/fact.png';
  static const String home = 'assets/images/home.png';
  static const String mythBusters = 'assets/images/myth-busters.png';
  static const String covid19AGlobalHealthCrisis =
      'assets/images/COVID-19-A-Global-Health-Crisis.jpg';
  static const String virus = 'assets/images/virus.png';
  static const String tierdness = 'assets/images/tierdness.png';
  static const String prevention = 'assets/images/prevention.png';
  static const String splash = 'assets/images/splash.jpg';
  static const String statistics = 'assets/images/statistics.png';
  static const String nasalCongestion = 'assets/images/nasal-congestion.png';
  static const String covid19PreventionDosAndDonts =
      'assets/images/COVID-19-Prevention-Dos-and-Donts.jpg';
  static const String genericError = 'assets/images/generic-error.png';
  static const String soreThroat = 'assets/images/sore-throat.png';
  static const String cough = 'assets/images/cough.png';
  static const String faq = 'assets/images/faq.png';
  static const String difficultyBreathing =
      'assets/images/difficulty-breathing.png';
  static const String myth = 'assets/images/myth.png';
  static const String fatigue = 'assets/images/fatigue.png';
  static const String headache = 'assets/images/headache.png';
  static const String symptoms = 'assets/images/symptoms.png';
}
