//// Generated by spider on 2020-05-08 16:49:04.364400

class AssetImages {
  static const String noInternet = 'assets/images/no-internet.png';
  static const String fact = 'assets/images/fact.png';
  static const String genericError = 'assets/images/generic-error.png';
  static const String myth = 'assets/images/myth.png';
}
